### ISSUE TITLE
die() prevents all plugins to uninstall

### ISSUE THREAD

**Issue by vnali** [24hoursmedia-craftcms/poll#10]
hi.
[this line](https://github.com/24hoursmedia-craftcms/poll/blob/6e6e235d5fdddf0049ee42edbf3e70da87e8279b/src/Poll.php#L171) prevents plugins to uninstall. it seems it has to be inside of plugin removal condition.

**Comment by 24hoursmedia-craftcms** [comment]
thank, you fix coming on!

**Comment by 24hoursmedia-craftcms** [comment]
@vnali update to the latest version and the issue has been fixed. Sorry for the inconvenience
