### ISSUE TITLE
Issue viewing results in the admin

### ISSUE THREAD

**Issue by alexr8** [24hoursmedia-craftcms/poll#24]
Hi, when i try viewing the results in the admin from the sidebar > poll then click on the poll i have created, i get the following error:

Unknown Method – yii\base\UnknownMethodException
Calling unknown method: twentyfourhoursmedia\poll\services\PollService::getResults()

I can output the results off my poll on the front-end using the example templates without any problem.

Craft 3.4.5
Poll 1.2.4

**Comment by 24hoursmedia-craftcms** [comment]
@alexr8 thank you, will fix this soon. There has been some refactoring in a recent version.

**Comment by 24hoursmedia-craftcms** [comment]
fixed in v1.2.5
