### ISSUE TITLE
getCsrfInput and getError

### ISSUE THREAD

**Issue by b3nhartl3y** [24hoursmedia-craftcms/poll#25]
Upon installing the plugin on Craft 3.5.12 I'm getting getCsrfInput and getError errors within Craft. Should be a quick update but it's currently unusable. 

Ben

**Comment by 24hoursmedia-craftcms** [comment]
Thank you, I’ll look into it as soon as possible!

 
Van: Ben Hartley <notifications@github.com>
Beantwoorden - Aan: 24hoursmedia-craftcms/poll <reply@reply.github.com>
Datum: dinsdag 13 oktober 2020 om 15:28
Aan: 24hoursmedia-craftcms/poll <poll@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [24hoursmedia-craftcms/poll] getCsrfInput and getError (#25)

 
Upon installing the plugin on Craft 3.5.12 I'm getting getCsrfInput and getError errors within Craft. Should be a quick update but it's currently unusable.

Ben

**Comment by b3nhartl3y** [comment]
Grand, there are lots of other elements that break on the newest version of
craft too 😭, I’ve spotted database errors as well when trying to export as
csv.

**Comment by 24HOURSMEDIA** [comment]
Tested and resolved issues on the latest craft v3.5.12.1 version in plugin version v1.5.0

**Comment by 24hoursmedia-craftcms** [comment]
Tested and resolved issues on the latest craft v3.5.12.1 version in plugin version v1.5.0
