### ISSUE TITLE
Used as a quiz as part of a digital product?

### ISSUE THREAD

**Issue by kevadamson** [24hoursmedia-craftcms/poll#27]
So my client creates content that is sold using Craft Commerce and the Digital Products plugin (https://plugins.craftcms.com/digital-products).

Can this plugin be used as a kind of quiz that can be included in a Digital Product? So the user would buy the digital product, read the content, then answer questions at the end as a test of what they have read. They can then see if they got them right. So the answers shown are tied to that user who has their own license for the digital product, and not a count of how everyone has answered, if that makes sense.

**Comment by 24HOURSMEDIA** [comment]
Hi @kevadamson 

Thanks for your interest, I am not that familiar with Craft Commerce and the Digital Products plugin unfortunately.

The answers of a logged in user are stored an a per user basis.
A poll (question + answers) is basically a regular content entry, with a matrix field in it.

The 'poll' entry as well as the 'answer matrix' are extensible in the sense that you could add extra fields ('right answer', 'answer weight', 'picture' etc). See https://io.24hoursmedia.com/craftcms-poll/customize-poll-entry

So I guess that you could relate one or more poll entries to another entry (product) with an Entries field.
And then make the user answer each of those 'poll questions' and collect the results.
As long as all question-answers are 'single' multiple choice answers.

It is not an out of the box solution though, so you should try and experiment yourself wether the plugin is not adapted for your specific use case.
