### ISSUE TITLE
Update for Craft 4?

### ISSUE THREAD

**Issue by adrienne** [24hoursmedia-craftcms/poll#41]
@eapbachman @24hoursmedia-craftcms  Are you planning to update this plugin for Craft 4? Have you abandoned it? I can take it over if you're looking for a maintainer.

**Comment by 24HOURSMEDIA** [comment]
Hi @adrienne I did not plan an update for Craft 4 on short term and I do not have a lot of time to add new features to this plugin. 

Generally I develop plugins for a single client within a project and then redistributed them, and keep the plugin features in sync with the new project requirements, unfortunately the client does not require new features and wishes to stay on Craft 3.

So I'd be happy to transfer ownership of the plugin. How do you envision a potential transfer?

**Comment by kringkaste** [comment]
Hi @24HOURSMEDIA! Have you come to an agreement? Otherwise, we can also offer to take over as a new maintainer.

**Comment by adrienne** [comment]
I would be happy to leave it to @kringkaste - I just would like to get it updated by *someone*.

**Comment by 24HOURSMEDIA** [comment]
@kringkaste thank you, that's ok with me, how shall we handle the transfer?

**Comment by adrienne** [comment]
@kringkaste @24HOURSMEDIA did this ever get handled?

I have a couple pull requests when it does happen. (Nothing Craft4-related but some multi-site fixes)
